modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/SignButton/issues"

[[mods]]
modId="signbutton"
version="${file.jarVersion}"
displayName="Sign Button"
description='''
A sign that is a button
'''
displayURL="https://github.com/gigaherz/SignButton"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.signbutton]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.0.0-alpha,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.signbutton]]
    modId="minecraft"
    type="required"
    versionRange="[26.1-alpha)"
    ordering="NONE"
    side="BOTH"